### ISSUE TITLE
Resource Types Remap

### ISSUE THREAD

**Issue by sharpattack** [galterlibrary/digital-repository#839]
There are some DigitalHub Resource Types that are mapped to multiple InvenioRDM Resource Types. We need to map to one of the multiple choices, and also mark it somehow for post-migration review. 

### TODO: select the invenioRDM mapping to use
- Abstracts 
  - [ ] Abstract
  - [x] Meeting Abstract
- Academic Dissertations
  - [ ] Bachelor Thesis
  - [ ] Masters Thesis
  - [x] Doctoral Thesis
- Article
  - [x] Journal Article
  - [ ] Newspaper Article
  - [ ] Other Article
- Audio Visual Document
  - [ ] Video
  - [x] Sound (Recording)
- Biography
  - [x] Biography
  - [ ] Personal Narrative
  - [ ] Diary
- Editorial Article
  - [x] Editorial
- Electronic Supplementary Materials
  - [ ] Chart
  - [ ] Table
  - [ ] Dataset
  - [ ] Bibliography
  - [ ] Technical Documentation
  - [x] Other <--- edit: Newly added mapping
- Guideline
  - [x] Guideline
  - [ ] Study Design
- Image
  - [x] Pictorial Work
- Introductory Journal Article
  - [x] Journal Article
  - [ ] Other Article
- Letter
  - [x] Letter
  - [ ] Correspondence
- Manuscript
  - [x] Manuscript
  - [ ] Preprint
- News
  - [ ] News
  - [x] Newsletter
- Other
  - [x] Other
  - [ ] Other Article
- Periodicals
  - [x] Newsletter
- Poster
  - [ ] Conference Poster
  - [ ] Other
  - [x] Poster <--- edit: Newly added mapping
- Programmed Instruction
  - [ ] Presentation
  - [ ] ...
  - [x] Instructional Film and Video <--- edit: Newly added mapping
- Research Paper
  - [ ] Report
  - [ ] Review
  - [x] Other Article
- Software or Program Code
  - [ ] Other
  - [x] Software
  - [ ] Technical Documentation
- Speech
  - [ ] Lecture
  - [ ] Presentation
  - [ ] Sound (Recording)
  - [x] (None) <--- edit: No mapping. Only usage in DigitalHub is on a Collection.

**Comment by sharpattack** [comment]
@saragon02 feel free to add to this list, or let me know if I am missing any.

**Comment by sharpattack** [comment]
Thanks @saragon for the updated remapping, with some new ones added. 

[ResourceTypes_DH_to_Invenio_Multi_type_Map_Post_LS_SG.xlsx](https://github.com/galterlibrary/digital-repository/files/6131039/ResourceTypes_DH_to_Invenio_Multi_type_Map_Post_LS_SG.xlsx)
